var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,d){if(b==Array.prototype||b==Object.prototype)return b;b[a]=d.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<b.length;++a){var d=b[a];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,a){var d=$jscomp.propertyToPolyfillSymbol[a];if(null==d)return b[a];d=b[d];return void 0!==d?d:b[a]};
$jscomp.polyfill=function(b,a,d,g){a&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,a,d,g):$jscomp.polyfillUnisolated(b,a,d,g))};$jscomp.polyfillUnisolated=function(b,a,d,g){d=$jscomp.global;b=b.split(".");for(g=0;g<b.length-1;g++){var e=b[g];if(!(e in d))return;d=d[e]}b=b[b.length-1];g=d[b];a=a(g);a!=g&&null!=a&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:a})};
$jscomp.polyfillIsolated=function(b,a,d,g){var e=b.split(".");b=1===e.length;g=e[0];g=!b&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var c=0;c<e.length-1;c++){var h=e[c];if(!(h in g))return;g=g[h]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?g[e]:null;a=a(d);null!=a&&(b?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:a}):a!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(g,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:a})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(b){if(b)return b;var a=function(e,c){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};a.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,g=function(e){if(this instanceof g)throw new TypeError("Symbol is not a constructor");return new a("jscomp_symbol_"+(e||"")+"_"+d++,e)};return g},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(b){if(b)return b;b=Symbol("Symbol.iterator");for(var a="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<a.length;d++){var g=$jscomp.global[a[d]];"function"===typeof g&&"function"!=typeof g.prototype[b]&&$jscomp.defineProperty(g.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return b},"es6",
"es3");$jscomp.iteratorPrototype=function(b){b={next:b};b[Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,a){b instanceof String&&(b+="");var d=0,g=!1,e={next:function(){if(!g&&d<b.length){var c=d++;return{value:a(c,b[c]),done:!1}}g=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
function decodeUplink(b){return{data:milesightDeviceDecode(b.bytes)}}function Decode(b,a){return milesightDeviceDecode(a)}function Decoder(b,a){return milesightDeviceDecode(b)}
function milesightDeviceDecode(b){for(var a={},d={},g=[],e={current:167772.15,voltage:655.35,forward_active_energy:4294967.295,reverse_active_energy:4294967.295,forward_reactive_energy:4294967.295,reverse_reactive_energy:4294967.295,apparent_energy:4294967.295,power_factor:2.55,active_power:-.001,reactive_power:-.001,apparent_power:-.001,thdi:655.35,thdv:655.35,voltage_three_phase_imbalcance:655.35},c={i:0};c.i<b.length;)switch(b[c.i++]){case 255:a.check_sequence_number_reply=a.check_sequence_number_reply||
{};a.check_sequence_number_reply.sequence_number=readUInt8(b,c,1);break;case 254:a.check_order_reply=readOnlyCommand(b,c,1);break;case 239:a.ans=a.ans||[];var h={},f=readUInt8(b,c,1);h.result=extractBits(f,4,8);h.length=extractBits(f,0,4);h.id=readCommand(b,c,h.length);a.ans.push(h);break;case 238:a.all_configurations_request_by_device=readOnlyCommand(b,c,0);break;case 237:if(0===g.length)for(var k in a)a.hasOwnProperty(k)&&(d[k]=a[k]);a={};readUInt8(b,c,1);a.timestamp=readUInt32LE(b,c,4);g.push(a);
break;case 207:a.lorawan_configuration_settings=a.lorawan_configuration_settings||{};216==readUInt8(b,c,1)&&(a.lorawan_configuration_settings.version=readUInt8(b,c,1));break;case 223:a.tsl_version=readProtocolVersion(readBytes(b,c,2));break;case 222:a.product_name=readString(b,c,32);break;case 221:a.product_pn=readString(b,c,32);break;case 219:a.product_sn=readHexString(b,c,8);break;case 218:a.version=a.version||{};a.version.hardware_version=readHardwareVersion(readBytes(b,c,2));a.version.firmware_version=
readFirmwareVersion(readBytes(b,c,6));break;case 217:a.oem_id=readHexString(b,c,2);break;case 216:a.product_frequency_band=readString(b,c,16);break;case 215:a.device_info=readOnlyCommand(b,c,72);break;case 1:a.temperature=readInt16LE(b,c,2)/100;break;case 2:a.voltage_three_phase_imbalcance=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage_three_phase_imbalcance);break;case 3:a.thdi=[];for(h=0;12>h;h++)f={},f.value=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.thdi),a.thdi.push(f);break;case 4:a.thdv=
[];for(h=0;3>h;h++)f={},f.value=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.thdv),a.thdv.push(f);break;case 5:a.current=[];for(h=0;12>h;h++)f={},f.value=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current),a.current.push(f);break;case 6:a.voltage=[];for(h=0;3>h;h++)f={},f.value=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage),a.voltage.push(f);break;case 7:a.power_factor=parseMaskBasedData(b,c,4,readUInt8,1,100,"power_factor",e);break;case 8:a.active_power1=parseMaskBasedData(b,c,2,readInt32LE,
4,1E3,"active_power",e);break;case 9:a.active_power2=parseMaskBasedData(b,c,2,readInt32LE,4,1E3,"active_power",e);break;case 10:a.reactive_power1=parseMaskBasedData(b,c,2,readInt32LE,4,1E3,"reactive_power",e);break;case 11:a.reactive_power2=parseMaskBasedData(b,c,2,readInt32LE,4,1E3,"reactive_power",e);break;case 12:a.apparent_power1=parseMaskBasedData(b,c,2,readInt32LE,4,1E3,"apparent_power",e);break;case 13:a.apparent_power2=parseMaskBasedData(b,c,2,readInt32LE,4,1E3,"apparent_power",e);break;case 14:a.forward_active_energy1=
parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"forward_active_energy",e);break;case 15:a.forward_active_energy2=parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"forward_active_energy",e);break;case 16:a.reverse_active_energy1=parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"reverse_active_energy",e);break;case 17:a.reverse_active_energy2=parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"reverse_active_energy",e);break;case 18:a.forward_reactive_energy1=parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"forward_reactive_energy",
e);break;case 19:a.forward_reactive_energy2=parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"forward_reactive_energy",e);break;case 20:a.reverse_reactive_energy1=parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"reverse_reactive_energy",e);break;case 21:a.reverse_reactive_energy2=parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"reverse_reactive_energy",e);break;case 22:a.apparent_energy1=parseMaskBasedData(b,c,2,readUInt32LE,4,1E3,"apparent_energy",e);break;case 23:a.apparent_energy2=parseMaskBasedData(b,c,2,
readUInt32LE,4,1E3,"apparent_energy",e);break;case 64:a.history_type=a.history_type||{};a.history_type.type=readUInt8(b,c,1);break;case 48:a.event=a.event||[];a.temperature_alarm={};a.temperature_alarm.type=readUInt8(b,c,1);0==a.temperature_alarm.type&&(a.temperature_alarm.collection_error=a.temperature_alarm.collection_error||{});1==a.temperature_alarm.type&&(a.temperature_alarm.lower_range_error=a.temperature_alarm.lower_range_error||{});2==a.temperature_alarm.type&&(a.temperature_alarm.over_range_error=
a.temperature_alarm.over_range_error||{});3==a.temperature_alarm.type&&(a.temperature_alarm.no_data=a.temperature_alarm.no_data||{});16==a.temperature_alarm.type&&(a.temperature_alarm.lower_range_alarm_deactivation=a.temperature_alarm.lower_range_alarm_deactivation||{},a.temperature_alarm.lower_range_alarm_deactivation.temperature=readWithErrorCheck(readInt16LE(b,c,2)/100,e.temperature));17==a.temperature_alarm.type&&(a.temperature_alarm.lower_range_alarm_trigger=a.temperature_alarm.lower_range_alarm_trigger||
{},a.temperature_alarm.lower_range_alarm_trigger.temperature=readWithErrorCheck(readInt16LE(b,c,2)/100,e.temperature));18==a.temperature_alarm.type&&(a.temperature_alarm.over_range_alarm_deactivation=a.temperature_alarm.over_range_alarm_deactivation||{},a.temperature_alarm.over_range_alarm_deactivation.temperature=readWithErrorCheck(readInt16LE(b,c,2)/100,e.temperature));19==a.temperature_alarm.type&&(a.temperature_alarm.over_range_alarm_trigger=a.temperature_alarm.over_range_alarm_trigger||{},a.temperature_alarm.over_range_alarm_trigger.temperature=
readWithErrorCheck(readInt16LE(b,c,2)/100,e.temperature));20==a.temperature_alarm.type&&(a.temperature_alarm.within_range_alarm_deactivation=a.temperature_alarm.within_range_alarm_deactivation||{},a.temperature_alarm.within_range_alarm_deactivation.temperature=readWithErrorCheck(readInt16LE(b,c,2)/100,e.temperature));21==a.temperature_alarm.type&&(a.temperature_alarm.within_range_alarm_trigger=a.temperature_alarm.within_range_alarm_trigger||{},a.temperature_alarm.within_range_alarm_trigger.temperature=
readWithErrorCheck(readInt16LE(b,c,2)/100,e.temperature));22==a.temperature_alarm.type&&(a.temperature_alarm.exceed_range_alarm_deactivation=a.temperature_alarm.exceed_range_alarm_deactivation||{},a.temperature_alarm.exceed_range_alarm_deactivation.temperature=readWithErrorCheck(readInt16LE(b,c,2)/100,e.temperature));23==a.temperature_alarm.type&&(a.temperature_alarm.exceed_range_alarm_trigger=a.temperature_alarm.exceed_range_alarm_trigger||{},a.temperature_alarm.exceed_range_alarm_trigger.temperature=
readWithErrorCheck(readInt16LE(b,c,2)/100,e.temperature));a.event.push(a.temperature_alarm);break;case 49:a.event=a.event||[];a.current_alarm={};a.current_alarm.channel=readUInt8(b,c,1);a.current_alarm.info=a.current_alarm.info||{};a.current_alarm.info.type=readUInt8(b,c,1);0==a.current_alarm.info.type&&(a.current_alarm.info.collection_error=a.current_alarm.info.collection_error||{});1==a.current_alarm.info.type&&(a.current_alarm.info.lower_range_error=a.current_alarm.info.lower_range_error||{},a.current_alarm.info.lower_range_error.current=
readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));2==a.current_alarm.info.type&&(a.current_alarm.info.over_range_error=a.current_alarm.info.over_range_error||{},a.current_alarm.info.over_range_error.current=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));3==a.current_alarm.info.type&&(a.current_alarm.info.no_data=a.current_alarm.info.no_data||{});4==a.current_alarm.info.type&&(a.current_alarm.info.over_range_release=a.current_alarm.info.over_range_release||{},a.current_alarm.info.over_range_release.current=
readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));16==a.current_alarm.info.type&&(a.current_alarm.info.lower_range_alarm_deactivation=a.current_alarm.info.lower_range_alarm_deactivation||{},a.current_alarm.info.lower_range_alarm_deactivation.current=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));17==a.current_alarm.info.type&&(a.current_alarm.info.lower_range_alarm_trigger=a.current_alarm.info.lower_range_alarm_trigger||{},a.current_alarm.info.lower_range_alarm_trigger.current=readWithErrorCheck(readUInt24LE(b,
c,3)/100,e.current));18==a.current_alarm.info.type&&(a.current_alarm.info.over_range_alarm_deactivation=a.current_alarm.info.over_range_alarm_deactivation||{},a.current_alarm.info.over_range_alarm_deactivation.current=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));19==a.current_alarm.info.type&&(a.current_alarm.info.over_range_alarm_trigger=a.current_alarm.info.over_range_alarm_trigger||{},a.current_alarm.info.over_range_alarm_trigger.current=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));
20==a.current_alarm.info.type&&(a.current_alarm.info.within_range_alarm_deactivation=a.current_alarm.info.within_range_alarm_deactivation||{},a.current_alarm.info.within_range_alarm_deactivation.current=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));21==a.current_alarm.info.type&&(a.current_alarm.info.within_range_alarm_trigger=a.current_alarm.info.within_range_alarm_trigger||{},a.current_alarm.info.within_range_alarm_trigger.current=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));
22==a.current_alarm.info.type&&(a.current_alarm.info.exceed_range_alarm_deactivation=a.current_alarm.info.exceed_range_alarm_deactivation||{},a.current_alarm.info.exceed_range_alarm_deactivation.current=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));23==a.current_alarm.info.type&&(a.current_alarm.info.exceed_range_alarm_trigger=a.current_alarm.info.exceed_range_alarm_trigger||{},a.current_alarm.info.exceed_range_alarm_trigger.current=readWithErrorCheck(readUInt24LE(b,c,3)/100,e.current));
a.event.push(a.current_alarm);break;case 50:a.event=a.event||[];a.voltage_alarm={};a.voltage_alarm.channel=readUInt8(b,c,1);a.voltage_alarm.info=a.voltage_alarm.info||{};a.voltage_alarm.info.type=readUInt8(b,c,1);0==a.voltage_alarm.info.type&&(a.voltage_alarm.info.collection_error=a.voltage_alarm.info.collection_error||{});1==a.voltage_alarm.info.type&&(a.voltage_alarm.info.lower_range_error=a.voltage_alarm.info.lower_range_error||{},a.voltage_alarm.info.lower_range_error.voltage=readWithErrorCheck(readUInt16LE(b,
c,2)/100,e.voltage));2==a.voltage_alarm.info.type&&(a.voltage_alarm.info.over_range_error=a.voltage_alarm.info.over_range_error||{},a.voltage_alarm.info.over_range_error.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage));3==a.voltage_alarm.info.type&&(a.voltage_alarm.info.no_data=a.voltage_alarm.info.no_data||{});4==a.voltage_alarm.info.type&&(a.voltage_alarm.info.over_range_release=a.voltage_alarm.info.over_range_release||{},a.voltage_alarm.info.over_range_release.voltage=readWithErrorCheck(readUInt16LE(b,
c,2)/100,e.voltage));16==a.voltage_alarm.info.type&&(a.voltage_alarm.info.lower_range_alarm_deactivation=a.voltage_alarm.info.lower_range_alarm_deactivation||{},a.voltage_alarm.info.lower_range_alarm_deactivation.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage));17==a.voltage_alarm.info.type&&(a.voltage_alarm.info.lower_range_alarm_trigger=a.voltage_alarm.info.lower_range_alarm_trigger||{},a.voltage_alarm.info.lower_range_alarm_trigger.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,
e.voltage));18==a.voltage_alarm.info.type&&(a.voltage_alarm.info.over_range_alarm_deactivation=a.voltage_alarm.info.over_range_alarm_deactivation||{},a.voltage_alarm.info.over_range_alarm_deactivation.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage));19==a.voltage_alarm.info.type&&(a.voltage_alarm.info.over_range_alarm_trigger=a.voltage_alarm.info.over_range_alarm_trigger||{},a.voltage_alarm.info.over_range_alarm_trigger.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage));
20==a.voltage_alarm.info.type&&(a.voltage_alarm.info.within_range_alarm_deactivation=a.voltage_alarm.info.within_range_alarm_deactivation||{},a.voltage_alarm.info.within_range_alarm_deactivation.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage));21==a.voltage_alarm.info.type&&(a.voltage_alarm.info.within_range_alarm_trigger=a.voltage_alarm.info.within_range_alarm_trigger||{},a.voltage_alarm.info.within_range_alarm_trigger.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage));
22==a.voltage_alarm.info.type&&(a.voltage_alarm.info.exceed_range_alarm_deactivation=a.voltage_alarm.info.exceed_range_alarm_deactivation||{},a.voltage_alarm.info.exceed_range_alarm_deactivation.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage));23==a.voltage_alarm.info.type&&(a.voltage_alarm.info.exceed_range_alarm_trigger=a.voltage_alarm.info.exceed_range_alarm_trigger||{},a.voltage_alarm.info.exceed_range_alarm_trigger.voltage=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage));
a.event.push(a.voltage_alarm);break;case 51:a.event=a.event||[];a.thdi_alarm={};a.thdi_alarm.channel=readUInt8(b,c,1);a.thdi_alarm.info=a.thdi_alarm.info||{};a.thdi_alarm.info.type=readUInt8(b,c,1);0==a.thdi_alarm.info.type&&(a.thdi_alarm.info.collection_error=a.thdi_alarm.info.collection_error||{});18==a.thdi_alarm.info.type&&(a.thdi_alarm.info.over_range_alarm_deactivation=a.thdi_alarm.info.over_range_alarm_deactivation||{},a.thdi_alarm.info.over_range_alarm_deactivation.thdi=readWithErrorCheck(readUInt16LE(b,
c,2)/100,e.thdi));19==a.thdi_alarm.info.type&&(a.thdi_alarm.info.over_range_alarm_trigger=a.thdi_alarm.info.over_range_alarm_trigger||{},a.thdi_alarm.info.over_range_alarm_trigger.thdi=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.thdi));a.event.push(a.thdi_alarm);break;case 52:a.event=a.event||[];a.thdv_alarm={};a.thdv_alarm.channel=readUInt8(b,c,1);a.thdv_alarm.info=a.thdv_alarm.info||{};a.thdv_alarm.info.type=readUInt8(b,c,1);0==a.thdv_alarm.info.type&&(a.thdv_alarm.info.collection_error=a.thdv_alarm.info.collection_error||
{});18==a.thdv_alarm.info.type&&(a.thdv_alarm.info.over_range_alarm_deactivation=a.thdv_alarm.info.over_range_alarm_deactivation||{},a.thdv_alarm.info.over_range_alarm_deactivation.thdv=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.thdv));19==a.thdv_alarm.info.type&&(a.thdv_alarm.info.over_range_alarm_trigger=a.thdv_alarm.info.over_range_alarm_trigger||{},a.thdv_alarm.info.over_range_alarm_trigger.thdv=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.thdv));a.event.push(a.thdv_alarm);break;case 53:a.event=
a.event||[];a.voltage_unbalance_alarm={};a.voltage_unbalance_alarm.type=readUInt8(b,c,1);0==a.voltage_unbalance_alarm.type&&(a.voltage_unbalance_alarm.collection_error=a.voltage_unbalance_alarm.collection_error||{});18==a.voltage_unbalance_alarm.type&&(a.voltage_unbalance_alarm.over_range_alarm_deactivation=a.voltage_unbalance_alarm.over_range_alarm_deactivation||{},a.voltage_unbalance_alarm.over_range_alarm_deactivation.voltage_unbalance=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage_unbalance));
19==a.voltage_unbalance_alarm.type&&(a.voltage_unbalance_alarm.over_range_alarm_trigger=a.voltage_unbalance_alarm.over_range_alarm_trigger||{},a.voltage_unbalance_alarm.over_range_alarm_trigger.voltage_unbalance=readWithErrorCheck(readUInt16LE(b,c,2)/100,e.voltage_unbalance));a.event.push(a.voltage_unbalance_alarm);break;case 54:a.power_loss_alarm=readOnlyCommand(b,c,0);break;case 96:a.collection_interval=a.collection_interval||{};a.collection_interval.unit=readUInt8(b,c,1);0==a.collection_interval.unit&&
(a.collection_interval.seconds_of_time=readUInt16LE(b,c,2));1==a.collection_interval.unit&&(a.collection_interval.minutes_of_time=readUInt16LE(b,c,2));break;case 97:a.reporting_interval=a.reporting_interval||{};a.reporting_interval.unit=readUInt8(b,c,1);0==a.reporting_interval.unit&&(a.reporting_interval.seconds_of_time=readUInt16LE(b,c,2));1==a.reporting_interval.unit&&(a.reporting_interval.minutes_of_time=readUInt16LE(b,c,2));break;case 200:a.device_status=readUInt8(b,c,1);break;case 99:a.temperature_unit=
readUInt8(b,c,1);break;case 100:a.bluetooth_name=a.bluetooth_name||{};a.bluetooth_name.length=readUInt8(b,c,1);a.bluetooth_name.content=readString(b,c,a.bluetooth_name.length);break;case 197:a.data_storage_settings=a.data_storage_settings||{};h=readUInt8(b,c,1);0==h&&(a.data_storage_settings.enable=readUInt8(b,c,1));1==h&&(a.data_storage_settings.retransmission_enable=readUInt8(b,c,1));2==h&&(a.data_storage_settings.retransmission_interval=readUInt16LE(b,c,2));3==h&&(a.data_storage_settings.retrieval_interval=
readUInt16LE(b,c,2));break;case 102:a.voltage_interface=readUInt8(b,c,1);break;case 103:a.current_interface1=a.current_interface1||{};a.current_interface1.type=readUInt8(b,c,1);a.current_interface1.config=[];for(h=0;3>h;h++)f={},f.direction=readUInt8(b,c,1),f.range=readUInt16LE(b,c,2),a.current_interface1.config.push(f);break;case 104:a.current_interface2=a.current_interface2||{};a.current_interface2.type=readUInt8(b,c,1);a.current_interface2.config=[];for(h=0;3>h;h++)f={},f.direction=readUInt8(b,
c,1),f.range=readUInt16LE(b,c,2),a.current_interface2.config.push(f);break;case 105:a.current_interface3=a.current_interface3||{};a.current_interface3.type=readUInt8(b,c,1);a.current_interface3.config=[];for(h=0;3>h;h++)f={},f.direction=readUInt8(b,c,1),f.range=readUInt16LE(b,c,2),a.current_interface3.config.push(f);break;case 106:a.current_interface4=a.current_interface4||{};a.current_interface4.type=readUInt8(b,c,1);a.current_interface4.config=[];for(h=0;3>h;h++)f={},f.direction=readUInt8(b,c,1),
f.range=readUInt16LE(b,c,2),a.current_interface4.config.push(f);break;case 107:a.temperature_calibration_settings=a.temperature_calibration_settings||{};a.temperature_calibration_settings.enable=readUInt8(b,c,1);a.temperature_calibration_settings.calibration_value=readInt16LE(b,c,2)/100;break;case 199:a.time_zone=readInt16LE(b,c,2);break;case 198:a.daylight_saving_time=a.daylight_saving_time||{};a.daylight_saving_time.enable=readUInt8(b,c,1);a.daylight_saving_time.daylight_saving_time_offset=readUInt8(b,
c,1);a.daylight_saving_time.start_month=readUInt8(b,c,1);f=readUInt8(b,c,1);a.daylight_saving_time.start_week_num=extractBits(f,4,8);a.daylight_saving_time.start_week_day=extractBits(f,0,4);a.daylight_saving_time.start_hour_min=readUInt16LE(b,c,2);a.daylight_saving_time.end_month=readUInt8(b,c,1);f=readUInt8(b,c,1);a.daylight_saving_time.end_week_num=extractBits(f,4,8);a.daylight_saving_time.end_week_day=extractBits(f,0,4);a.daylight_saving_time.end_hour_min=readUInt16LE(b,c,2);break;case 118:a.temperature_alarm_settings=
a.temperature_alarm_settings||{};a.temperature_alarm_settings.enable=readUInt8(b,c,1);a.temperature_alarm_settings.threshold_condition=readUInt8(b,c,1);a.temperature_alarm_settings.threshold_min=readInt16LE(b,c,2)/100;a.temperature_alarm_settings.threshold_max=readInt16LE(b,c,2)/100;break;case 119:a.current_alarm_settings=a.current_alarm_settings||[];h=readUInt8(b,c,1);f=pickArrayItem(a.current_alarm_settings,h,"channel");f.channel=h;insertArrayItem(a.current_alarm_settings,f,"channel");f.enable=
readUInt8(b,c,1);f.threshold_condition=readUInt8(b,c,1);f.threshold_min=readInt16LE(b,c,2);f.threshold_max=readInt16LE(b,c,2);break;case 120:a.voltage_alarm_settings=a.voltage_alarm_settings||[];h=readUInt8(b,c,1);f=pickArrayItem(a.voltage_alarm_settings,h,"channel");f.channel=h;insertArrayItem(a.voltage_alarm_settings,f,"channel");f.enable=readUInt8(b,c,1);f.threshold_condition=readUInt8(b,c,1);f.threshold_min=readInt16LE(b,c,2);f.threshold_max=readInt16LE(b,c,2);break;case 121:a.thdi_alarm_settings=
a.thdi_alarm_settings||[];h=readUInt8(b,c,1);f=pickArrayItem(a.thdi_alarm_settings,h,"channel");f.channel=h;insertArrayItem(a.thdi_alarm_settings,f,"channel");f.enable=readUInt8(b,c,1);f.threshold_condition=readUInt8(b,c,1);f.threshold_min=readInt16LE(b,c,2);f.threshold_max=readInt16LE(b,c,2);break;case 122:a.thdv_alarm_settings=a.thdv_alarm_settings||[];h=readUInt8(b,c,1);f=pickArrayItem(a.thdv_alarm_settings,h,"channel");f.channel=h;insertArrayItem(a.thdv_alarm_settings,f,"channel");f.enable=readUInt8(b,
c,1);f.threshold_condition=readUInt8(b,c,1);f.threshold_min=readInt16LE(b,c,2);f.threshold_max=readInt16LE(b,c,2);break;case 123:a.voltage_unbalance_alarm_settings=a.voltage_unbalance_alarm_settings||{};a.voltage_unbalance_alarm_settings.enable=readUInt8(b,c,1);a.voltage_unbalance_alarm_settings.threshold_condition=readUInt8(b,c,1);a.voltage_unbalance_alarm_settings.threshold_min=readInt16LE(b,c,2);a.voltage_unbalance_alarm_settings.threshold_max=readInt16LE(b,c,2);break;case 124:a.alarm_global_settings=
a.alarm_global_settings||{};a.alarm_global_settings.interval=readUInt16LE(b,c,2);a.alarm_global_settings.times=readUInt16LE(b,c,2);a.alarm_global_settings.release_enable=readUInt8(b,c,1);break;case 109:a.month_statistics_settings=a.month_statistics_settings||{};a.month_statistics_settings.day=readUInt8(b,c,1);a.month_statistics_settings.hour=readUInt8(b,c,1);a.month_statistics_settings.minute=readUInt8(b,c,1);break;case 108:a.report_enable=a.report_enable||{};f=readUInt16LE(b,c,2);a.report_enable.temperature=
extractBits(f,0,1);a.report_enable.current=extractBits(f,1,2);a.report_enable.voltage=extractBits(f,2,3);a.report_enable.power_factor=extractBits(f,3,4);a.report_enable.active_power=extractBits(f,4,5);a.report_enable.reactive_power=extractBits(f,5,6);a.report_enable.apparent_power=extractBits(f,6,7);a.report_enable.forward_active_energy=extractBits(f,7,8);a.report_enable.reverse_active_energy=extractBits(f,8,9);a.report_enable.forward_reactive_energy=extractBits(f,9,10);a.report_enable.reverse_reactive_energy=
extractBits(f,10,11);a.report_enable.apparent_energy=extractBits(f,11,12);a.report_enable.thdi=extractBits(f,12,13);a.report_enable.thdv=extractBits(f,13,14);a.report_enable.voltage_unbalance=extractBits(f,14,15);break;case 191:a.reset=readOnlyCommand(b,c,0);break;case 190:a.reboot=readOnlyCommand(b,c,0);break;case 93:a.stop_historical_data_retrieval=a.stop_historical_data_retrieval||{};a.stop_historical_data_retrieval.type=readUInt8(b,c,1);break;case 91:a.retrieve_historical_data_by_time=a.retrieve_historical_data_by_time||
{};a.retrieve_historical_data_by_time.type=readUInt8(b,c,1);a.retrieve_historical_data_by_time.time=readUInt32LE(b,c,4);break;case 92:a.retrieve_historical_data_by_time_range=a.retrieve_historical_data_by_time_range||{};a.retrieve_historical_data_by_time_range.type=readUInt8(b,c,1);a.retrieve_historical_data_by_time_range.start_time=readUInt32LE(b,c,4);a.retrieve_historical_data_by_time_range.end_time=readUInt32LE(b,c,4);break;case 185:a.query_device_status=readOnlyCommand(b,c,0);break;case 184:a.synchronize_time=
readOnlyCommand(b,c,0);break;case 183:a.set_time=a.set_time||{};a.set_time.timestamp=readUInt32LE(b,c,4);break;case 182:a.reconnect=readOnlyCommand(b,c,0);break;case 95:a.reset_energy=a.reset_energy||{};a.reset_energy.channel=readUInt8(b,c,1);break;case 94:a.clear_data=a.clear_data||{};a.clear_data.type=readUInt8(b,c,1);break;case 87:a.query_history_set=readOnlyCommand(b,c,0)}if(0<Object.keys(g).length)d.history=g;else for(var n in a)a.hasOwnProperty(n)&&(d[n]=a[n]);return d}
function readOnlyCommand(b){return 1}function readUnknownDataType(b,a,d){throw Error("Unknown data type encountered. Please Contact Developer.");}function readBytes(b,a,d){b=b.slice(a.i,a.i+d);a.i+=d;return b}function readProtocolVersion(b){return"v"+(b[0]&255)+"."+(b[1]&255)}function readHardwareVersion(b){return"v"+(b[0]&255)+"."+(b[1]&255)}
function readFirmwareVersion(b){var a=b[2]&255,d=b[3]&255,g=b[4]&255,e=b[5]&255;b="v"+(b[0]&255)+"."+(b[1]&255);0!==a&&(b+="-r"+a);0!==d&&(b+="-a"+d);0!==g&&(b+="-u"+g);0!==e&&(b+="-t"+e);return b}function readUInt8(b,a,d){return readBytes(b,a,d)[0]&255}function readInt8(b,a,d){b=readUInt8(b,a,d);return 127<b?b-256:b}function readUInt16LE(b,a,d){b=readBytes(b,a,d);return(b[1]<<8)+b[0]&65535}function readInt16LE(b,a,d){b=readUInt16LE(b,a,d);return 32767<b?b-65536:b}
function readWithErrorCheck(b,a){return b==a?"error":b}function parseMaskBasedData(b,a,d,g,e,c,h,f){for(var k={},n=readUInt8(b,a,1),l=1;l<=d;l++){var m="mask"+l;k[m]=extractBits(n,l-1,l);0==k[m]&&(k["group"+l+"_value"]=readWithErrorCheck(g(b,a,e)/c,f[h]));if(1==k[m])for(k["group"+l]={},m=1;3>=m;m++)k["group"+l]["chan"+m]=readWithErrorCheck(g(b,a,e)/c,f[h])}return k}function readUInt24LE(b,a,d){b=readBytes(b,a,d);return(b[2]<<16)+(b[1]<<8)+b[0]&16777215}
function readInt24LE(b,a,d){b=readUInt24LE(b,a,d);return 8388607<b?b-16777216:b}function readUInt32LE(b,a,d){b=readBytes(b,a,d);return((b[3]<<24)+(b[2]<<16)+(b[1]<<8)+b[0]&4294967295)>>>0}function readInt32LE(b,a,d){b=readUInt32LE(b,a,d);return 2147483647<b?b-4294967296:b}function readFloat16LE(b,a,d){b=readBytes(b,a,d);b=b[1]<<8|b[0];a=b>>>10&31;return Number(((0===b>>>15?1:-1)*(0===a?(b&1023)<<1:b&1023|1024)*Math.pow(2,a-25)).toFixed(2))}
function readFloatLE(b,a,d){b=readBytes(b,a,d);b=b[3]<<24|b[2]<<16|b[1]<<8|b[0];a=b>>>23&255;return(0===b>>>31?1:-1)*(0===a?(b&8388607)<<1:b&8388607|8388608)*Math.pow(2,a-150)}
function readString(b,a,d){var g="";b=readBytes(b,a,d);a=0;for(var e,c,h;a<b.length;)d=b[a++],127>=d?g+=String.fromCharCode(d):223>=d?(e=b[a++],g+=String.fromCharCode((d&31)<<6|e&63)):239>=d?(e=b[a++],c=b[a++],g+=String.fromCharCode((d&15)<<12|(e&63)<<6|c&63)):247>=d&&(e=b[a++],c=b[a++],h=b[a++],d=(d&7)<<18|(e&63)<<12|(c&63)<<6|h&63,d-=65536,g+=String.fromCharCode((d>>10)+55296),g+=String.fromCharCode((d&1023)+56320));return g.replace(/\u0000+$/g,"")}
function readHexString(b,a,d){var g=[];b=readBytes(b,a,d);for(a=0;a<b.length;a++)g.push(("0"+(b[a]&255).toString(16)).slice(-2));return g.join("").replace(/\u0000+$/g,"")}function readHexStringLE(b,a,d){var g=[];b=readBytes(b,a,d);for(a=b.length-1;0<=a;a--)g.push(("0"+(b[a]&255).toString(16)).slice(-2));return g.join("").replace(/\u0000+$/g,"")}
function extractBits(b,a,d){if(0>b||65535<b)throw Error("byte must be in range 0..65535");if(a>=d)throw Error("invalid bit range");return b>>>a&(1<<d-a)-1}function pickArrayItem(b,a,d){for(var g=0;g<b.length;g++)if(b[g][d]===a)return b[g];return{}}function insertArrayItem(b,a,d){for(var g=0;g<b.length;g++)if(b[g][d]===a[d]){b[g]=a;return}b.push(a)}
function readCommand(b,a,d){b=readBytes(b,a,d).map(function(k){k=k.toString(16);return 1===k.length?"0"+k:k}).join("").toLowerCase();a=cmdMap();for(var g in a){var e=[],c=!1;if(g.length===b.length){for(d=0;d<g.length;d+=2){c=g.slice(d,d+2);var h=b.slice(d,d+2);if(c===h||"xx"===c)"xx"===c&&e.push("."+parseInt(h,16)),c=!0;else{c=!1;break}}if(c){g=a[g];if(-1===g.indexOf("._item"))return g;var f=0;return g.replace(/\._item/g,function(){return e[f++]})}}}return null}
function cmdMap(){return{10:"reverse_active_energy1",11:"reverse_active_energy2",12:"forward_reactive_energy1",13:"forward_reactive_energy2",14:"reverse_reactive_energy1",15:"reverse_reactive_energy2",16:"apparent_energy1",17:"apparent_energy2",30:"temperature_alarm",31:"current_alarm",32:"voltage_alarm",33:"thdi_alarm",34:"thdv_alarm",35:"voltage_unbalance_alarm",36:"power_loss_alarm",40:"history_type",57:"query_history_set",60:"collection_interval",61:"reporting_interval",63:"temperature_unit",
64:"bluetooth_name",66:"voltage_interface",67:"current_interface1",68:"current_interface2",69:"current_interface3",76:"temperature_alarm_settings",77:"current_alarm_settings",78:"voltage_alarm_settings",79:"thdi_alarm_settings",ff:"request_check_sequence_number",fe:"request_check_order",ef:"request_command_queries",ee:"request_query_all_configurations",ed:"historical_data_report",cf:"lorawan_configuration_settings",cfd8:"lorawan_configuration_settings.version",df:"tsl_version",de:"product_name",dd:"product_pn",
db:"product_sn",da:"version",d9:"oem_id",d8:"product_frequency_band",d7:"device_info","01":"temperature","02":"voltage_three_phase_imbalcance","03":"thdi","03xx":"thdi._item","04":"thdv","04xx":"thdv._item","05":"current","05xx":"current._item","06":"voltage","06xx":"voltage._item","07":"power_factor","08":"active_power1","09":"active_power2","0a":"reactive_power1","0b":"reactive_power2","0c":"apparent_power1","0d":"apparent_power2","0e":"forward_active_energy1","0f":"forward_active_energy2",c8:"device_status",
c5:"data_storage_settings",c500:"data_storage_settings.enable",c501:"data_storage_settings.retransmission_enable",c502:"data_storage_settings.retransmission_interval",c503:"data_storage_settings.retrieval_interval",undefinedxx:"current_interface4.config._item","6a":"current_interface4","6b":"temperature_calibration_settings",c7:"time_zone",c6:"daylight_saving_time","77xx":"current_alarm_settings._item","78xx":"voltage_alarm_settings._item","79xx":"thdi_alarm_settings._item","7a":"thdv_alarm_settings",
"7axx":"thdv_alarm_settings._item","7b":"voltage_unbalance_alarm_settings","7c":"alarm_global_settings","6d":"month_statistics_settings","6c":"report_enable",bf:"reset",be:"reboot","5d":"stop_historical_data_retrieval","5b":"retrieve_historical_data_by_time","5c":"retrieve_historical_data_by_time_range",b9:"query_device_status",b8:"synchronize_time",b7:"set_time",b6:"reconnect","5f":"reset_energy","5e":"clear_data"}};
