function encodeDownlink(a){return{bytes:milesightDeviceEncode(a.data)}}function Encode(a,c){return milesightDeviceEncode(c)}function Encoder(a,c){return milesightDeviceEncode(a)}
function milesightDeviceEncode(a){var c=[],f=[255,255,255],d=[255,255],e=[255,255,255,255],l=[255,255,255,255],v=[255,255,255,255],m=[255,255,255,255],n=[255,255,255,255],k=[255],r=[255,255,255,255],B=[255,255,255,255],C=[255,255,255,255],w=[255,255],x=[255,255],y=[255,255];if("request_check_sequence_number"in a){var b=new Buffer;b.writeUInt8(255);if(0>a.request_check_sequence_number.sequence_number||255<a.request_check_sequence_number.sequence_number)throw Error("request_check_sequence_number.sequence_number must be between 0 and 255");
b.writeUInt8(a.request_check_sequence_number.sequence_number);c=c.concat(b.toBytes())}if("request_check_order"in a){b=new Buffer;b.writeUInt8(254);if(0>a.request_check_order.order||255<a.request_check_order.order)throw Error("request_check_order.order must be between 0 and 255");b.writeUInt8(a.request_check_order.order);c=c.concat(b.toBytes())}if("req"in a){b=new Buffer;for(var t=a.req,u=0;u<t.length;u++){var z=[],A=[];t[u].split(".").forEach(function(p){if(/^[0-9]+$/.test(p)){for(p=Number(p).toString(16);2>
p.length;)p="0"+p;z.push(p);console.log(z);A.push("_item")}else A.push(p)});var q=A.join(".");if((q=cmdMap()[q])&&-1!==q.indexOf("xx")){var g=0;q=q.replace(/xx/g,function(){return z[g++]})}if(q){var D=q.length/2;b.writeUInt8(239);b.writeUInt8(D);b.writeHexString(q,D,!0)}}c=c.concat(b.toBytes())}"request_query_all_configurations"in a&&(b=new Buffer,b.writeUInt8(238),c=c.concat(b.toBytes()));if("history"in a)for(g=0;g<a.history.length;g++){b=new Buffer;t=a.history[g];b.writeUInt8(237);b.writeUInt8(1);
b.writeUInt32LE(t.timestamp);u={};for(var h in t)t.hasOwnProperty(h)&&"timestamp"!==h&&(u[h]=t[h]);c=c.concat(b.toBytes());c=c.concat(milesightDeviceEncode(u))}"lorawan_configuration_settings"in a&&(b=new Buffer,isValid(a.lorawan_configuration_settings.version)&&(b.writeUInt8(207),b.writeUInt8(216),b.writeUInt8(a.lorawan_configuration_settings.version)),c=c.concat(b.toBytes()));"product_name"in a&&(b=new Buffer,b.writeUInt8(222),b.writeString(a.product_name,32),c=c.concat(b.toBytes()));"product_pn"in
a&&(b=new Buffer,b.writeUInt8(221),b.writeString(a.product_pn,32),c=c.concat(b.toBytes()));"product_sn"in a&&(b=new Buffer,b.writeUInt8(219),b.writeHexString(a.product_sn,8),c=c.concat(b.toBytes()));"oem_id"in a&&(b=new Buffer,b.writeUInt8(217),b.writeHexString(a.oem_id,2),c=c.concat(b.toBytes()));"product_frequency_band"in a&&(b=new Buffer,b.writeUInt8(216),b.writeString(a.product_frequency_band,16),c=c.concat(b.toBytes()));"device_info"in a&&(b=new Buffer,b.writeUInt8(215),c=c.concat(b.toBytes()));
if("temperature"in a){b=new Buffer;b.writeUInt8(1);if(-20>a.temperature||100<a.temperature)throw Error("temperature must be between -20 and 100");b.writeInt16LE(100*a.temperature);c=c.concat(b.toBytes())}if("voltage_three_phase_imbalcance"in a){b=new Buffer;b.writeUInt8(2);if("error"===a.voltage_three_phase_imbalcance)b.writeBytes(y);else{if(0>a.voltage_three_phase_imbalcance||100<a.voltage_three_phase_imbalcance)throw Error("voltage_three_phase_imbalcance must be between 0 and 100");b.writeUInt16LE(100*
a.voltage_three_phase_imbalcance)}c=c.concat(b.toBytes())}if("thdi"in a){b=new Buffer;b.writeUInt8(3);for(g=0;g<a.thdi.length;g++)if(h=a.thdi[g],"error"===h.value)b.writeBytes(w);else{if(0>h.value||100<h.value)throw Error("value must be between 0 and 100");b.writeUInt16LE(100*h.value)}c=c.concat(b.toBytes())}if("thdv"in a){b=new Buffer;b.writeUInt8(4);for(g=0;g<a.thdv.length;g++)if(h=a.thdv[g],"error"===h.value)b.writeBytes(x);else{if(0>h.value||100<h.value)throw Error("value must be between 0 and 100");
b.writeUInt16LE(100*h.value)}c=c.concat(b.toBytes())}if("current"in a){b=new Buffer;b.writeUInt8(5);for(g=0;g<a.current.length;g++)if(h=a.current[g],"error"===h.value)b.writeBytes(f);else{if(0>h.value||4E3<h.value)throw Error("value must be between 0 and 4000");b.writeUInt24LE(100*h.value)}c=c.concat(b.toBytes())}if("voltage"in a){b=new Buffer;b.writeUInt8(6);for(g=0;g<a.voltage.length;g++)if(f=a.voltage[g],"error"===f.value)b.writeBytes(d);else{if(0>f.value||500<f.value)throw Error("value must be between 0 and 500");
b.writeUInt16LE(100*f.value)}c=c.concat(b.toBytes())}"power_factor"in a&&(b=encodeMaskBasedData("power_factor",a.power_factor,7,4,Buffer.prototype.writeUInt8,100,k,{min:0,max:100}),c=c.concat(b.toBytes()));"active_power1"in a&&(b=encodeMaskBasedData("active_power1",a.active_power1,8,2,Buffer.prototype.writeInt32LE,1E3,r,null),c=c.concat(b.toBytes()));"active_power2"in a&&(b=encodeMaskBasedData("active_power2",a.active_power2,9,2,Buffer.prototype.writeInt32LE,1E3,r,null),c=c.concat(b.toBytes()));"reactive_power1"in
a&&(b=encodeMaskBasedData("reactive_power1",a.reactive_power1,10,2,Buffer.prototype.writeInt32LE,1E3,B,null),c=c.concat(b.toBytes()));"reactive_power2"in a&&(b=encodeMaskBasedData("reactive_power2",a.reactive_power2,11,2,Buffer.prototype.writeInt32LE,1E3,B,null),c=c.concat(b.toBytes()));"apparent_power1"in a&&(b=encodeMaskBasedData("apparent_power1",a.apparent_power1,12,2,Buffer.prototype.writeInt32LE,1E3,C,null),c=c.concat(b.toBytes()));"apparent_power2"in a&&(b=encodeMaskBasedData("apparent_power2",
a.apparent_power2,13,2,Buffer.prototype.writeInt32LE,1E3,C,null),c=c.concat(b.toBytes()));"forward_active_energy1"in a&&(b=encodeMaskBasedData("forward_active_energy1",a.forward_active_energy1,14,2,Buffer.prototype.writeUInt32LE,1E3,e,null),c=c.concat(b.toBytes()));"forward_active_energy2"in a&&(b=encodeMaskBasedData("forward_active_energy2",a.forward_active_energy2,15,2,Buffer.prototype.writeUInt32LE,1E3,e,null),c=c.concat(b.toBytes()));"reverse_active_energy1"in a&&(b=encodeMaskBasedData("reverse_active_energy1",
a.reverse_active_energy1,16,2,Buffer.prototype.writeUInt32LE,1E3,l,null),c=c.concat(b.toBytes()));"reverse_active_energy2"in a&&(b=encodeMaskBasedData("reverse_active_energy2",a.reverse_active_energy2,17,2,Buffer.prototype.writeUInt32LE,1E3,l,null),c=c.concat(b.toBytes()));"forward_reactive_energy1"in a&&(b=encodeMaskBasedData("forward_reactive_energy1",a.forward_reactive_energy1,18,2,Buffer.prototype.writeUInt32LE,1E3,v,null),c=c.concat(b.toBytes()));"forward_reactive_energy2"in a&&(b=encodeMaskBasedData("forward_reactive_energy2",
a.forward_reactive_energy2,19,2,Buffer.prototype.writeUInt32LE,1E3,v,null),c=c.concat(b.toBytes()));"reverse_reactive_energy1"in a&&(b=encodeMaskBasedData("reverse_reactive_energy1",a.reverse_reactive_energy1,20,2,Buffer.prototype.writeUInt32LE,1E3,m,null),c=c.concat(b.toBytes()));"reverse_reactive_energy2"in a&&(b=encodeMaskBasedData("reverse_reactive_energy2",a.reverse_reactive_energy2,21,2,Buffer.prototype.writeUInt32LE,1E3,m,null),c=c.concat(b.toBytes()));"apparent_energy1"in a&&(b=encodeMaskBasedData("apparent_energy1",
a.apparent_energy1,22,2,Buffer.prototype.writeUInt32LE,1E3,n,null),c=c.concat(b.toBytes()));"apparent_energy2"in a&&(b=encodeMaskBasedData("apparent_energy2",a.apparent_energy2,23,2,Buffer.prototype.writeUInt32LE,1E3,n,null),c=c.concat(b.toBytes()));"history_type"in a&&(b=new Buffer,b.writeUInt8(64),b.writeUInt8(a.history_type.type),c=c.concat(b.toBytes()));if("temperature_alarm"in a){b=new Buffer;b.writeUInt8(48);b.writeUInt8(a.temperature_alarm.type);if(16==a.temperature_alarm.type){if(-20>a.temperature_alarm.lower_range_alarm_deactivation.temperature||
100<a.temperature_alarm.lower_range_alarm_deactivation.temperature)throw Error("temperature_alarm.lower_range_alarm_deactivation.temperature must be between -20 and 100");b.writeInt16LE(100*a.temperature_alarm.lower_range_alarm_deactivation.temperature)}if(17==a.temperature_alarm.type){if(-20>a.temperature_alarm.lower_range_alarm_trigger.temperature||100<a.temperature_alarm.lower_range_alarm_trigger.temperature)throw Error("temperature_alarm.lower_range_alarm_trigger.temperature must be between -20 and 100");
b.writeInt16LE(100*a.temperature_alarm.lower_range_alarm_trigger.temperature)}if(18==a.temperature_alarm.type){if(-20>a.temperature_alarm.over_range_alarm_deactivation.temperature||100<a.temperature_alarm.over_range_alarm_deactivation.temperature)throw Error("temperature_alarm.over_range_alarm_deactivation.temperature must be between -20 and 100");b.writeInt16LE(100*a.temperature_alarm.over_range_alarm_deactivation.temperature)}if(19==a.temperature_alarm.type){if(-20>a.temperature_alarm.over_range_alarm_trigger.temperature||
100<a.temperature_alarm.over_range_alarm_trigger.temperature)throw Error("temperature_alarm.over_range_alarm_trigger.temperature must be between -20 and 100");b.writeInt16LE(100*a.temperature_alarm.over_range_alarm_trigger.temperature)}if(20==a.temperature_alarm.type){if(-20>a.temperature_alarm.within_range_alarm_deactivation.temperature||100<a.temperature_alarm.within_range_alarm_deactivation.temperature)throw Error("temperature_alarm.within_range_alarm_deactivation.temperature must be between -20 and 100");
b.writeInt16LE(100*a.temperature_alarm.within_range_alarm_deactivation.temperature)}if(21==a.temperature_alarm.type){if(-20>a.temperature_alarm.within_range_alarm_trigger.temperature||100<a.temperature_alarm.within_range_alarm_trigger.temperature)throw Error("temperature_alarm.within_range_alarm_trigger.temperature must be between -20 and 100");b.writeInt16LE(100*a.temperature_alarm.within_range_alarm_trigger.temperature)}if(22==a.temperature_alarm.type){if(-20>a.temperature_alarm.exceed_range_alarm_deactivation.temperature||
100<a.temperature_alarm.exceed_range_alarm_deactivation.temperature)throw Error("temperature_alarm.exceed_range_alarm_deactivation.temperature must be between -20 and 100");b.writeInt16LE(100*a.temperature_alarm.exceed_range_alarm_deactivation.temperature)}if(23==a.temperature_alarm.type){if(-20>a.temperature_alarm.exceed_range_alarm_trigger.temperature||100<a.temperature_alarm.exceed_range_alarm_trigger.temperature)throw Error("temperature_alarm.exceed_range_alarm_trigger.temperature must be between -20 and 100");
b.writeInt16LE(100*a.temperature_alarm.exceed_range_alarm_trigger.temperature)}c=c.concat(b.toBytes())}if("current_alarm"in a){b=new Buffer;b.writeUInt8(49);if(0>a.current_alarm.channel||11<a.current_alarm.channel)throw Error("current_alarm.channel must be between 0 and 11");b.writeUInt8(a.current_alarm.channel);b.writeUInt8(a.current_alarm.info.type);1==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.lower_range_error.current);2==a.current_alarm.info.type&&b.writeUInt24LE(100*
a.current_alarm.info.over_range_error.current);4==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.over_range_release.current);16==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.lower_range_alarm_deactivation.current);17==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.lower_range_alarm_trigger.current);18==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.over_range_alarm_deactivation.current);19==a.current_alarm.info.type&&
b.writeUInt24LE(100*a.current_alarm.info.over_range_alarm_trigger.current);20==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.within_range_alarm_deactivation.current);21==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.within_range_alarm_trigger.current);22==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.exceed_range_alarm_deactivation.current);23==a.current_alarm.info.type&&b.writeUInt24LE(100*a.current_alarm.info.exceed_range_alarm_trigger.current);
c=c.concat(b.toBytes())}if("voltage_alarm"in a){b=new Buffer;b.writeUInt8(50);if(0>a.voltage_alarm.channel||11<a.voltage_alarm.channel)throw Error("voltage_alarm.channel must be between 0 and 11");b.writeUInt8(a.voltage_alarm.channel);b.writeUInt8(a.voltage_alarm.info.type);1==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.lower_range_error.voltage);2==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.over_range_error.voltage);4==a.voltage_alarm.info.type&&b.writeUInt16LE(100*
a.voltage_alarm.info.over_range_release.voltage);16==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.lower_range_alarm_deactivation.voltage);17==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.lower_range_alarm_trigger.voltage);18==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.over_range_alarm_deactivation.voltage);19==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.over_range_alarm_trigger.voltage);20==a.voltage_alarm.info.type&&
b.writeUInt16LE(100*a.voltage_alarm.info.within_range_alarm_deactivation.voltage);21==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.within_range_alarm_trigger.voltage);22==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.exceed_range_alarm_deactivation.voltage);23==a.voltage_alarm.info.type&&b.writeUInt16LE(100*a.voltage_alarm.info.exceed_range_alarm_trigger.voltage);c=c.concat(b.toBytes())}if("thdi_alarm"in a){b=new Buffer;b.writeUInt8(51);if(0>a.thdi_alarm.channel||
11<a.thdi_alarm.channel)throw Error("thdi_alarm.channel must be between 0 and 11");b.writeUInt8(a.thdi_alarm.channel);b.writeUInt8(a.thdi_alarm.info.type);18==a.thdi_alarm.info.type&&("error"===a.thdi_alarm.info.over_range_alarm_deactivation.thdi?b.writeBytes(w):b.writeUInt16LE(100*a.thdi_alarm.info.over_range_alarm_deactivation.thdi));19==a.thdi_alarm.info.type&&("error"===a.thdi_alarm.info.over_range_alarm_trigger.thdi?b.writeBytes(w):b.writeUInt16LE(100*a.thdi_alarm.info.over_range_alarm_trigger.thdi));
c=c.concat(b.toBytes())}if("thdv_alarm"in a){b=new Buffer;b.writeUInt8(52);if(0>a.thdv_alarm.channel||11<a.thdv_alarm.channel)throw Error("thdv_alarm.channel must be between 0 and 11");b.writeUInt8(a.thdv_alarm.channel);b.writeUInt8(a.thdv_alarm.info.type);18==a.thdv_alarm.info.type&&("error"===a.thdv_alarm.info.over_range_alarm_deactivation.thdv?b.writeBytes(x):b.writeUInt16LE(100*a.thdv_alarm.info.over_range_alarm_deactivation.thdv));19==a.thdv_alarm.info.type&&("error"===a.thdv_alarm.info.over_range_alarm_trigger.thdv?
b.writeBytes(x):b.writeUInt16LE(100*a.thdv_alarm.info.over_range_alarm_trigger.thdv));c=c.concat(b.toBytes())}"voltage_unbalance_alarm"in a&&(b=new Buffer,b.writeUInt8(53),b.writeUInt8(a.voltage_unbalance_alarm.type),18==a.voltage_unbalance_alarm.type&&("error"===a.voltage_unbalance_alarm.over_range_alarm_deactivation.voltage_unbalance?b.writeBytes(y):b.writeUInt16LE(100*a.voltage_unbalance_alarm.over_range_alarm_deactivation.voltage_unbalance)),19==a.voltage_unbalance_alarm.type&&("error"===a.voltage_unbalance_alarm.over_range_alarm_trigger.voltage_unbalance?
b.writeBytes(y):b.writeUInt16LE(100*a.voltage_unbalance_alarm.over_range_alarm_trigger.voltage_unbalance)),c=c.concat(b.toBytes()));"power_loss_alarm"in a&&(b=new Buffer,b.writeUInt8(54),c=c.concat(b.toBytes()));if("collection_interval"in a){b=new Buffer;b.writeUInt8(96);b.writeUInt8(a.collection_interval.unit);if(0==a.collection_interval.unit){if(10>a.collection_interval.seconds_of_time||64800<a.collection_interval.seconds_of_time)throw Error("collection_interval.seconds_of_time must be between 10 and 64800");
b.writeUInt16LE(a.collection_interval.seconds_of_time)}if(1==a.collection_interval.unit){if(1>a.collection_interval.minutes_of_time||1440<a.collection_interval.minutes_of_time)throw Error("collection_interval.minutes_of_time must be between 1 and 1440");b.writeUInt16LE(a.collection_interval.minutes_of_time)}c=c.concat(b.toBytes())}if("reporting_interval"in a){b=new Buffer;b.writeUInt8(97);b.writeUInt8(a.reporting_interval.unit);if(0==a.reporting_interval.unit){if(10>a.reporting_interval.seconds_of_time||
64800<a.reporting_interval.seconds_of_time)throw Error("reporting_interval.seconds_of_time must be between 10 and 64800");b.writeUInt16LE(a.reporting_interval.seconds_of_time)}if(1==a.reporting_interval.unit){if(1>a.reporting_interval.minutes_of_time||1440<a.reporting_interval.minutes_of_time)throw Error("reporting_interval.minutes_of_time must be between 1 and 1440");b.writeUInt16LE(a.reporting_interval.minutes_of_time)}c=c.concat(b.toBytes())}"device_status"in a&&(b=new Buffer,b.writeUInt8(200),
b.writeUInt8(a.device_status),c=c.concat(b.toBytes()));"temperature_unit"in a&&(b=new Buffer,b.writeUInt8(99),b.writeUInt8(a.temperature_unit),c=c.concat(b.toBytes()));if("bluetooth_name"in a){b=new Buffer;b.writeUInt8(100);if(1>a.bluetooth_name.length||13<a.bluetooth_name.length)throw Error("bluetooth_name.length must be between 1 and 13");b.writeUInt8(a.bluetooth_name.length);b.writeString(a.bluetooth_name.content,a.bluetooth_name.length,!0);c=c.concat(b.toBytes())}if("data_storage_settings"in a){b=
new Buffer;isValid(a.data_storage_settings.enable)&&(b.writeUInt8(197),b.writeUInt8(0),b.writeUInt8(a.data_storage_settings.enable));isValid(a.data_storage_settings.retransmission_enable)&&(b.writeUInt8(197),b.writeUInt8(1),b.writeUInt8(a.data_storage_settings.retransmission_enable));if(isValid(a.data_storage_settings.retransmission_interval)){b.writeUInt8(197);b.writeUInt8(2);if(30>a.data_storage_settings.retransmission_interval||1200<a.data_storage_settings.retransmission_interval)throw Error("data_storage_settings.retransmission_interval must be between 30 and 1200");
b.writeUInt16LE(a.data_storage_settings.retransmission_interval)}if(isValid(a.data_storage_settings.retrieval_interval)){b.writeUInt8(197);b.writeUInt8(3);if(30>a.data_storage_settings.retrieval_interval||1200<a.data_storage_settings.retrieval_interval)throw Error("data_storage_settings.retrieval_interval must be between 30 and 1200");b.writeUInt16LE(a.data_storage_settings.retrieval_interval)}c=c.concat(b.toBytes())}"voltage_interface"in a&&(b=new Buffer,b.writeUInt8(102),b.writeUInt8(a.voltage_interface),
c=c.concat(b.toBytes()));if("current_interface1"in a){b=new Buffer;b.writeUInt8(103);b.writeUInt8(a.current_interface1.type);for(g=0;g<a.current_interface1.config.length;g++)d=a.current_interface1.config[g],b.writeUInt8(d.direction),b.writeUInt16LE(d.range);c=c.concat(b.toBytes())}if("current_interface2"in a){b=new Buffer;b.writeUInt8(104);b.writeUInt8(a.current_interface2.type);for(g=0;g<a.current_interface2.config.length;g++)d=a.current_interface2.config[g],b.writeUInt8(d.direction),b.writeUInt16LE(d.range);
c=c.concat(b.toBytes())}if("current_interface3"in a){b=new Buffer;b.writeUInt8(105);b.writeUInt8(a.current_interface3.type);for(g=0;g<a.current_interface3.config.length;g++)d=a.current_interface3.config[g],b.writeUInt8(d.direction),b.writeUInt16LE(d.range);c=c.concat(b.toBytes())}if("current_interface4"in a){b=new Buffer;b.writeUInt8(106);b.writeUInt8(a.current_interface4.type);for(g=0;g<a.current_interface4.config.length;g++)d=a.current_interface4.config[g],b.writeUInt8(d.direction),b.writeUInt16LE(d.range);
c=c.concat(b.toBytes())}if("temperature_calibration_settings"in a){b=new Buffer;b.writeUInt8(107);b.writeUInt8(a.temperature_calibration_settings.enable);if(-120>a.temperature_calibration_settings.calibration_value||120<a.temperature_calibration_settings.calibration_value)throw Error("temperature_calibration_settings.calibration_value must be between -120 and 120");b.writeInt16LE(100*a.temperature_calibration_settings.calibration_value);c=c.concat(b.toBytes())}"time_zone"in a&&(b=new Buffer,b.writeUInt8(199),
b.writeInt16LE(a.time_zone),c=c.concat(b.toBytes()));if("daylight_saving_time"in a){b=new Buffer;b.writeUInt8(198);b.writeUInt8(a.daylight_saving_time.enable);if(0>a.daylight_saving_time.daylight_saving_time_offset||120<a.daylight_saving_time.daylight_saving_time_offset)throw Error("daylight_saving_time.daylight_saving_time_offset must be between 0 and 120");b.writeUInt8(a.daylight_saving_time.daylight_saving_time_offset);b.writeUInt8(a.daylight_saving_time.start_month);d=0|a.daylight_saving_time.start_week_num<<
4;d|=a.daylight_saving_time.start_week_day<<0;b.writeUInt8(d);b.writeUInt16LE(a.daylight_saving_time.start_hour_min);b.writeUInt8(a.daylight_saving_time.end_month);d=0|a.daylight_saving_time.end_week_num<<4;d|=a.daylight_saving_time.end_week_day<<0;b.writeUInt8(d);b.writeUInt16LE(a.daylight_saving_time.end_hour_min);c=c.concat(b.toBytes())}if("temperature_alarm_settings"in a){b=new Buffer;b.writeUInt8(118);b.writeUInt8(a.temperature_alarm_settings.enable);b.writeUInt8(a.temperature_alarm_settings.threshold_condition);
if(-20>a.temperature_alarm_settings.threshold_min||100<a.temperature_alarm_settings.threshold_min)throw Error("temperature_alarm_settings.threshold_min must be between -20 and 100");b.writeInt16LE(100*a.temperature_alarm_settings.threshold_min);if(-20>a.temperature_alarm_settings.threshold_max||100<a.temperature_alarm_settings.threshold_max)throw Error("temperature_alarm_settings.threshold_max must be between -20 and 100");b.writeInt16LE(100*a.temperature_alarm_settings.threshold_max);c=c.concat(b.toBytes())}if("current_alarm_settings"in
a){b=new Buffer;for(d=0;d<(a.current_alarm_settings&&a.current_alarm_settings.length);d++){e=a.current_alarm_settings[d];l=e.channel;b.writeUInt8(119);b.writeUInt8(l);b.writeUInt8(e.enable);b.writeUInt8(e.threshold_condition);if(0>e.threshold_min||4E3<e.threshold_min)throw Error("threshold_min must be between 0 and 4000");b.writeInt16LE(e.threshold_min);if(0>e.threshold_max||4E3<e.threshold_max)throw Error("threshold_max must be between 0 and 4000");b.writeInt16LE(e.threshold_max)}c=c.concat(b.toBytes())}if("voltage_alarm_settings"in
a){b=new Buffer;for(d=0;d<(a.voltage_alarm_settings&&a.voltage_alarm_settings.length);d++){e=a.voltage_alarm_settings[d];l=e.channel;b.writeUInt8(120);b.writeUInt8(l);b.writeUInt8(e.enable);b.writeUInt8(e.threshold_condition);if(0>e.threshold_min||500<e.threshold_min)throw Error("threshold_min must be between 0 and 500");b.writeInt16LE(e.threshold_min);if(0>e.threshold_max||500<e.threshold_max)throw Error("threshold_max must be between 0 and 500");b.writeInt16LE(e.threshold_max)}c=c.concat(b.toBytes())}if("thdi_alarm_settings"in
a){b=new Buffer;for(d=0;d<(a.thdi_alarm_settings&&a.thdi_alarm_settings.length);d++){e=a.thdi_alarm_settings[d];l=e.channel;b.writeUInt8(121);b.writeUInt8(l);b.writeUInt8(e.enable);b.writeUInt8(e.threshold_condition);if(0>e.threshold_min||100<e.threshold_min)throw Error("threshold_min must be between 0 and 100");b.writeInt16LE(e.threshold_min);if(1>e.threshold_max||100<e.threshold_max)throw Error("threshold_max must be between 1 and 100");b.writeInt16LE(e.threshold_max)}c=c.concat(b.toBytes())}if("thdv_alarm_settings"in
a){b=new Buffer;for(d=0;d<(a.thdv_alarm_settings&&a.thdv_alarm_settings.length);d++){e=a.thdv_alarm_settings[d];l=e.channel;b.writeUInt8(122);b.writeUInt8(l);b.writeUInt8(e.enable);b.writeUInt8(e.threshold_condition);if(0>e.threshold_min||100<e.threshold_min)throw Error("threshold_min must be between 0 and 100");b.writeInt16LE(e.threshold_min);if(1>e.threshold_max||100<e.threshold_max)throw Error("threshold_max must be between 1 and 100");b.writeInt16LE(e.threshold_max)}c=c.concat(b.toBytes())}if("voltage_unbalance_alarm_settings"in
a){b=new Buffer;b.writeUInt8(123);b.writeUInt8(a.voltage_unbalance_alarm_settings.enable);b.writeUInt8(a.voltage_unbalance_alarm_settings.threshold_condition);if(0>a.voltage_unbalance_alarm_settings.threshold_min||100<a.voltage_unbalance_alarm_settings.threshold_min)throw Error("voltage_unbalance_alarm_settings.threshold_min must be between 0 and 100");b.writeInt16LE(a.voltage_unbalance_alarm_settings.threshold_min);if(1>a.voltage_unbalance_alarm_settings.threshold_max||100<a.voltage_unbalance_alarm_settings.threshold_max)throw Error("voltage_unbalance_alarm_settings.threshold_max must be between 1 and 100");
b.writeInt16LE(a.voltage_unbalance_alarm_settings.threshold_max);c=c.concat(b.toBytes())}if("alarm_global_settings"in a){b=new Buffer;b.writeUInt8(124);if(1>a.alarm_global_settings.interval||1440<a.alarm_global_settings.interval)throw Error("alarm_global_settings.interval must be between 1 and 1440");b.writeUInt16LE(a.alarm_global_settings.interval);if(1>a.alarm_global_settings.times||1E3<a.alarm_global_settings.times)throw Error("alarm_global_settings.times must be between 1 and 1000");b.writeUInt16LE(a.alarm_global_settings.times);
b.writeUInt8(a.alarm_global_settings.release_enable);c=c.concat(b.toBytes())}if("month_statistics_settings"in a){b=new Buffer;b.writeUInt8(109);if(1>a.month_statistics_settings.day||28<a.month_statistics_settings.day)throw Error("month_statistics_settings.day must be between 1 and 28");b.writeUInt8(a.month_statistics_settings.day);if(0>a.month_statistics_settings.hour||23<a.month_statistics_settings.hour)throw Error("month_statistics_settings.hour must be between 0 and 23");b.writeUInt8(a.month_statistics_settings.hour);
if(0>a.month_statistics_settings.minute||59<a.month_statistics_settings.minute)throw Error("month_statistics_settings.minute must be between 0 and 59");b.writeUInt8(a.month_statistics_settings.minute);c=c.concat(b.toBytes())}"report_enable"in a&&(b=new Buffer,b.writeUInt8(108),d=0|a.report_enable.temperature<<0,d|=a.report_enable.current<<1,d|=a.report_enable.voltage<<2,d|=a.report_enable.power_factor<<3,d|=a.report_enable.active_power<<4,d|=a.report_enable.reactive_power<<5,d|=a.report_enable.apparent_power<<
6,d|=a.report_enable.forward_active_energy<<7,d|=a.report_enable.reverse_active_energy<<8,d|=a.report_enable.forward_reactive_energy<<9,d|=a.report_enable.reverse_reactive_energy<<10,d|=a.report_enable.apparent_energy<<11,d|=a.report_enable.thdi<<12,d|=a.report_enable.thdv<<13,d|=a.report_enable.voltage_unbalance<<14,b.writeUInt16LE(d),c=c.concat(b.toBytes()));"reset"in a&&(b=new Buffer,b.writeUInt8(191),c=c.concat(b.toBytes()));"reboot"in a&&(b=new Buffer,b.writeUInt8(190),c=c.concat(b.toBytes()));
"stop_historical_data_retrieval"in a&&(b=new Buffer,b.writeUInt8(93),b.writeUInt8(a.stop_historical_data_retrieval.type),c=c.concat(b.toBytes()));"retrieve_historical_data_by_time"in a&&(b=new Buffer,b.writeUInt8(91),b.writeUInt8(a.retrieve_historical_data_by_time.type),b.writeUInt32LE(a.retrieve_historical_data_by_time.time),c=c.concat(b.toBytes()));"retrieve_historical_data_by_time_range"in a&&(b=new Buffer,b.writeUInt8(92),b.writeUInt8(a.retrieve_historical_data_by_time_range.type),b.writeUInt32LE(a.retrieve_historical_data_by_time_range.start_time),
b.writeUInt32LE(a.retrieve_historical_data_by_time_range.end_time),c=c.concat(b.toBytes()));"query_device_status"in a&&(b=new Buffer,b.writeUInt8(185),c=c.concat(b.toBytes()));"synchronize_time"in a&&(b=new Buffer,b.writeUInt8(184),c=c.concat(b.toBytes()));"set_time"in a&&(b=new Buffer,b.writeUInt8(183),b.writeUInt32LE(a.set_time.timestamp),c=c.concat(b.toBytes()));"reconnect"in a&&(b=new Buffer,b.writeUInt8(182),c=c.concat(b.toBytes()));if("reset_energy"in a){b=new Buffer;b.writeUInt8(95);if(0>a.reset_energy.channel||
12<a.reset_energy.channel)throw Error("reset_energy.channel must be between 0 and 12");b.writeUInt8(a.reset_energy.channel);c=c.concat(b.toBytes())}"clear_data"in a&&(b=new Buffer,b.writeUInt8(94),b.writeUInt8(a.clear_data.type),c=c.concat(b.toBytes()));"query_history_set"in a&&(b=new Buffer,b.writeUInt8(87),c=c.concat(b.toBytes()));return c}
function encodeMaskBasedData(a,c,f,d,e,l,v,m){var n=new Buffer;n.writeUInt8(f);var k=0;for(f=1;f<=d;f++)k|=c["mask"+f]<<f-1;n.writeUInt8(k);for(f=1;f<=d;f++){if(0==c["mask"+f])if(k=c["group"+f+"_value"],"error"===k)n.writeBytes(v);else{if(m&&(k<m.min||k>m.max))throw Error(a+".group"+f+"_value must be between "+m.min+" and "+m.max);e.call(n,k*l)}if(1==c["mask"+f])for(var r=1;3>=r;r++)if(k=c["group"+f]["chan"+r],"error"===k)n.writeBytes(v);else{if(m&&(k<m.min||k>m.max))throw Error(a+".group"+f+".chan"+
r+" must be between "+m.min+" and "+m.max);e.call(n,k*l)}}return n}function Buffer(){this.buffer=[]}Buffer.prototype._write=function(a,c,f){a=Math.round(a);for(var d,e=0;e<c;e++)d=f?e<<3:c-1-e<<3,this.buffer.push(a>>d&255)};Buffer.prototype.writeUInt8=function(a){this._write(a,1,!0)};Buffer.prototype.writeInt8=function(a){this._write(0>a?a+256:a,1,!0)};Buffer.prototype.writeUInt16LE=function(a){this._write(a,2,!0)};Buffer.prototype.writeInt16LE=function(a){this._write(0>a?a+65536:a,2,!0)};
Buffer.prototype.writeUInt24LE=function(a){this._write(a,3,!0)};Buffer.prototype.writeInt24LE=function(a){this._write(0>a?a+16777216:a,3,!0)};Buffer.prototype.writeUInt32LE=function(a){this._write(a,4,!0)};Buffer.prototype.writeInt32LE=function(a){this._write(0>a?a+4294967296:a,4,!0)};
Buffer.prototype.writeBytes=function(a,c,f){void 0===f&&(f=!1);if(c<a.length)throw Error("bytes length is greater than length");if(f&&a.length!=c)throw Error("bytes length is not equal to length");for(f=0;f<a.length;f++)this.buffer.push(a[f]);if(c>a.length)for(f=a.length;f<c;f++)this.buffer.push(0)};
Buffer.prototype.writeHexString=function(a,c,f){void 0===f&&(f=!1);for(var d=[],e=0;e<a.length;e+=2)d.push(parseInt(a.substr(e,2),16));if(f&&d.length!=c)throw Error("hex string length is not equal to length");this.writeBytes(d,c)};Buffer.prototype.writeString=function(a,c,f){void 0===f&&(f=!1);a=encodeUtf8(a);if(f&&a.length!=c)throw Error("string length is not equal to length");this.writeBytes(a,c)};
Buffer.prototype.writeUnknownDataType=function(a){throw Error("Unknown data type encountered. Please Contact Developer.");};Buffer.prototype.writeHexStringReverse=function(a,c,f){void 0===f&&(f=!1);for(var d=[],e=a.length-2;0<=e;e-=2)d.push(parseInt(a.substr(e,2),16));if(f&&d.length!=c)throw Error("hex string length is not equal to length");this.writeBytes(d,c)};Buffer.prototype.toBytes=function(){return this.buffer};
function encodeUtf8(a){for(var c=[],f=0;f<a.length;f++){var d=a.charCodeAt(f);128>d?c.push(d):2048>d?(c.push(192|d>>6),c.push(128|d&63)):65536>d?(c.push(224|d>>12),c.push(128|d>>6&63),c.push(128|d&63)):2097152>d&&(c.push(240|d>>18),c.push(128|d>>12&63),c.push(128|d>>6&63),c.push(128|d&63))}return c}function isValid(a){return void 0!==a&&null!==a&&""!==a}
function cmdMap(){return{request_check_sequence_number:"ff",request_check_order:"fe",request_command_queries:"ef",request_query_all_configurations:"ee",historical_data_report:"ed",lorawan_configuration_settings:"cf","lorawan_configuration_settings.version":"cfd8",tsl_version:"df",product_name:"de",product_pn:"dd",product_sn:"db",version:"da",oem_id:"d9",product_frequency_band:"d8",device_info:"d7",temperature:"01",voltage_three_phase_imbalcance:"02",thdi:"03","thdi._item":"03xx",thdv:"04","thdv._item":"04xx",
current:"05","current._item":"05xx",voltage:"06","voltage._item":"06xx",power_factor:"07",active_power1:"08",active_power2:"09",reactive_power1:"0a",reactive_power2:"0b",apparent_power1:"0c",apparent_power2:"0d",forward_active_energy1:"0e",forward_active_energy2:"0f",reverse_active_energy1:"10",reverse_active_energy2:"11",forward_reactive_energy1:"12",forward_reactive_energy2:"13",reverse_reactive_energy1:"14",reverse_reactive_energy2:"15",apparent_energy1:"16",apparent_energy2:"17",history_type:"40",
temperature_alarm:"30",current_alarm:"31",voltage_alarm:"32",thdi_alarm:"33",thdv_alarm:"34",voltage_unbalance_alarm:"35",power_loss_alarm:"36",collection_interval:"60",reporting_interval:"61",device_status:"c8",temperature_unit:"63",bluetooth_name:"64",data_storage_settings:"c5","data_storage_settings.enable":"c500","data_storage_settings.retransmission_enable":"c501","data_storage_settings.retransmission_interval":"c502","data_storage_settings.retrieval_interval":"c503",voltage_interface:"66",current_interface1:"67",
"current_interface1.config._item":"undefinedxx",current_interface2:"68","current_interface2.config._item":"undefinedxx",current_interface3:"69","current_interface3.config._item":"undefinedxx",current_interface4:"6a","current_interface4.config._item":"undefinedxx",temperature_calibration_settings:"6b",time_zone:"c7",daylight_saving_time:"c6",temperature_alarm_settings:"76",current_alarm_settings:"77","current_alarm_settings._item":"77xx",voltage_alarm_settings:"78","voltage_alarm_settings._item":"78xx",
thdi_alarm_settings:"79","thdi_alarm_settings._item":"79xx",thdv_alarm_settings:"7a","thdv_alarm_settings._item":"7axx",voltage_unbalance_alarm_settings:"7b",alarm_global_settings:"7c",month_statistics_settings:"6d",report_enable:"6c",reset:"bf",reboot:"be",stop_historical_data_retrieval:"5d",retrieve_historical_data_by_time:"5b",retrieve_historical_data_by_time_range:"5c",query_device_status:"b9",synchronize_time:"b8",set_time:"b7",reconnect:"b6",reset_energy:"5f",clear_data:"5e",query_history_set:"57"}}
;
